### ISSUE TITLE
Test failures: not enough IP addresses

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#136]
See kubeflow/kubeflow#837

```
 message: "{\"ResourceType\":\"container.v1.cluster\",\"ResourceErrorCode\":\"403\"\
   ,\"ResourceErrorMessage\":{\"code\":403,\"message\":\"Insufficient regional quota\
   \ to satisfy request for resource: \\\"IN_USE_ADDRESSES\\\". The request requires\
   \ '1.0' and is short '1.0'. The regional quota is '32.0' with '0.0' available.\"\
   ,\"status\":\"PERMISSION_DENIED\",\"statusMessage\":\"Forbidden\",\"requestPath\"\
   :\"https://container.googleapis.com/v1/projects/kubeflow-ci/zones/us-east1-d/clusters\"\
   ,\"httpMethod\":\"POST\"}}"
```

Current quota.

```
gcloud --project=kubeflow-ci compute regions describe us-east1
creationTimestamp: '1969-12-31T16:00:00.000-08:00'
description: us-east1
id: '1230'
kind: compute#region
name: us-east1
quotas:
- limit: 320.0
  metric: CPUS
  usage: 232.0
- limit: 16384.0
  metric: DISKS_TOTAL_GB
  usage: 10415.0
- limit: 8.0
  metric: STATIC_ADDRESSES
  usage: 0.0
- limit: 32.0
  metric: IN_USE_ADDRESSES
  usage: 18.0
- limit: 500.0
  metric: SSD_TOTAL_GB
  usage: 10.0
- limit: 6000.0
  metric: LOCAL_SSD_TOTAL_GB
  usage: 0.0
- limit: 100.0
  metric: INSTANCE_GROUPS
  usage: 75.0
- limit: 50.0
  metric: INSTANCE_GROUP_MANAGERS
  usage: 2.0
- limit: 3200.0
  metric: INSTANCES
  usage: 18.0
- limit: 50.0
  metric: AUTOSCALERS
  usage: 0.0
- limit: 20.0
  metric: REGIONAL_AUTOSCALERS
  usage: 0.0
- limit: 20.0
  metric: REGIONAL_INSTANCE_GROUP_MANAGERS
  usage: 0.0
- limit: 0.0
  metric: PREEMPTIBLE_CPUS
  usage: 0.0
- limit: 24.0
  metric: NVIDIA_K80_GPUS
  usage: 4.0
- limit: 0.0
  metric: COMMITMENTS
  usage: 0.0
- limit: 200.0
  metric: INTERNAL_ADDRESSES
  usage: 0.0
- limit: 0.0
  metric: NVIDIA_P100_GPUS
  usage: 0.0
- limit: 0.0
  metric: PREEMPTIBLE_LOCAL_SSD_GB
  usage: 0.0
- limit: 0.0
  metric: PREEMPTIBLE_NVIDIA_K80_GPUS
  usage: 0.0
- limit: 0.0
  metric: PREEMPTIBLE_NVIDIA_P100_GPUS
  usage: 0.0
- limit: 0.0
  metric: NVIDIA_V100_GPUS
  usage: 0.0
selfLink: https://www.googleapis.com/compute/v1/projects/kubeflow-ci/regions/us-east1
status: UP
zones:
- https://www.googleapis.com/compute/v1/projects/kubeflow-ci/zones/us-east1-b
- https://www.googleapis.com/compute/v1/projects/kubeflow-ci/zones/us-east1-c
- https://www.googleapis.com/compute/v1/projects/kubeflow-ci/zones/us-east1-d
```
