### ISSUE TITLE
label sync failing

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#221]
Our label sync job doesn't appear to be running.

We recently added a 0.4.0 label and I didn't see it added to some repos.

related to kubeflow/community#173

**Comment by jlewi** [comment]
Cronjob is setup in
project:kubeflow-ci
cluster: kubeflow-testing

**Comment by jlewi** [comment]
Most recent job run failed

```
piVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: 2018-09-28T12:00:03Z
  labels:
    app: label-sync
  name: label-sync-cron-1538136000
  namespace: kubeflow-test-infra
  ownerReferences:
  - apiVersion: batch/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: CronJob
    name: label-sync-cron
    uid: 999789d9-4812-11e8-93a9-42010af0000d
  resourceVersion: "44280962"
  selfLink: /apis/batch/v1/namespaces/kubeflow-test-infra/jobs/label-sync-cron-1538136000
  uid: 086f612e-c316-11e8-a8da-42010af000c9
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: 086f612e-c316-11e8-a8da-42010af000c9
  template:
    metadata:
      creationTimestamp: null
      labels:
        controller-uid: 086f612e-c316-11e8-a8da-42010af000c9
        job-name: label-sync-cron-1538136000
    spec:
      containers:
      - args:
        - --config=/etc/config/kubeflow_label.yml
        - --confirm=true
        - --orgs=kubeflow
        - --token=/etc/github/bot-token
        image: gcr.io/k8s-testimages/label_sync:v20180227-377685119
        imagePullPolicy: IfNotPresent
        name: label-sync
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/github
          name: oauth
          readOnly: true
        - mountPath: /etc/config
          name: config
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: oauth
        secret:
          defaultMode: 420
          secretName: bot-token-github
      - configMap:
          defaultMode: 420
          name: label-config-v2
        name: config
status:
  conditions:
  - lastProbeTime: 2018-09-28T16:52:47Z
    lastTransitionTime: 2018-09-28T16:52:47Z
    message: Job has reach the specified backoff limit
    reason: BackoffLimitExceeded
    status: "True"
    type: Failed
  failed: 6
  startTime: 2018-09-28T12:00:03Z

```

**Comment by jlewi** [comment]
Here's the error

```
time="2018-09-28T21:57:34Z" level=fatal msg="failed to update kubeflow" error="failed to list labels: [status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [200], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#update-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [200], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#update-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [200], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#update-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [200], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#update-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [200], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#update-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [200], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#update-a-label\"} status code 404 not one of [200], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#update-a-label\"} status code 404 not one of [200], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#update-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [200], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#update-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [200], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#update-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"} status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/issues/labels/#create-a-label\"}]"
```

**Comment by jlewi** [comment]
I upgraded to the latest label sync image from Kubernetes. It is now running successfully; output is below. But it doesn't seem like any labels are getting updated.

```
ime="2018-09-29T00:05:05Z" level=info msg="Throttle(300, 100)" client=github 
time="2018-09-29T00:05:05Z" level=info msg="Reading repos" org=kubeflow 
time="2018-09-29T00:05:05Z" level=info msg="GetRepos(kubeflow, false)" client=github 
time="2018-09-29T00:05:05Z" level=info msg="Found 22 repos" org=kubeflow 
time="2018-09-29T00:05:05Z" level=info msg="Listing labels for repo" org=kubeflow repo=kubeflow 
time="2018-09-29T00:05:05Z" level=info msg="GetRepoLabels(kubeflow, kubeflow)" client=github 
time="2018-09-29T00:05:05Z" level=info msg="Listing labels for repo" org=kubeflow repo=tf-operator 
time="2018-09-29T00:05:05Z" level=info msg="GetRepoLabels(kubeflow, tf-operator)" client=github 
time="2018-09-29T00:05:05Z" level=info msg="Listing labels for repo" org=kubeflow repo=reporting 
time="2018-09-29T00:05:05Z" level=info msg="Listing labels for repo" org=kubeflow repo=community 
time="2018-09-29T00:05:05Z" level=info msg="GetRepoLabels(kubeflow, reporting)" client=github 
time="2018-09-29T00:05:05Z" level=info msg="GetRepoLabels(kubeflow, community)" client=github 
time="2018-09-29T00:05:05Z" level=info msg="Listing labels for repo" org=kubeflow repo=pytorch-operator 
time="2018-09-29T00:05:05Z" level=info msg="GetRepoLabels(kubeflow, pytorch-operator)" client=github 
time="2018-09-29T00:05:05Z" level=info msg="Listing labels for repo" org=kubeflow repo=caffe2-operator 
time="2018-09-29T00:05:05Z" level=info msg="GetRepoLabels(kubeflow, caffe2-operator)" client=github 
time="2018-09-29T00:05:05Z" level=info msg="Listing labels for repo" org=kubeflow repo=katib 
time="2018-09-29T00:05:05Z" level=info msg="GetRepoLabels(kubeflow, katib)" client=github 
time="2018-09-29T00:05:05Z" level=info msg="Listing labels for repo" org=kubeflow repo=website 
time="2018-09-29T00:05:05Z" level=info msg="GetRepoLabels(kubeflow, website)" client=github 
time="2018-09-29T00:05:05Z" level=info msg="Listing labels for repo" org=kubeflow repo=example-seldon 
time="2018-09-29T00:05:05Z" level=info msg="GetRepoLabels(kubeflow, example-seldon)" client=github 
time="2018-09-29T00:05:05Z" level=info msg="Listing labels for repo" org=kubeflow repo=kubebench 
time="2018-09-29T00:05:05Z" level=info msg="GetRepoLabels(kubeflow, kubebench)" client=github 
time="2018-09-29T00:05:05Z" level=info msg="Listing labels for repo" org=kubeflow repo=batch-predict 
time="2018-09-29T00:05:05Z" level=info msg="GetRepoLabels(kubeflow, batch-predict)" client=github 
time="2018-09-29T00:05:05Z" level=info msg="Listing labels for repo" org=kubeflow repo=internal-acls 
time="2018-09-29T00:05:05Z" level=info msg="Listing labels for repo" org=kubeflow repo=pipelines 
time="2018-09-29T00:05:05Z" level=info msg="Listing labels for repo" org=kubeflow repo=mpi-operator 
time="2018-09-29T00:05:05Z" level=info msg="GetRepoLabels(kubeflow, mpi-operator)" client=github 
time="2018-09-29T00:05:05Z" level=info msg="GetRepoLabels(kubeflow, pipelines)" client=github 
time="2018-09-29T00:05:05Z" level=info msg="Listing labels for repo" org=kubeflow repo=crd-validation 
time="2018-09-29T00:05:05Z" level=info msg="GetRepoLabels(kubeflow, crd-validation)" client=github 
time="2018-09-29T00:05:05Z" level=info msg="Listing labels for repo" org=kubeflow repo=testing 
time="2018-09-29T00:05:05Z" level=info msg="GetRepoLabels(kubeflow, testing)" client=github 
time="2018-09-29T00:05:05Z" level=info msg="Listing labels for repo" org=kubeflow repo=chainer-operator 
time="2018-09-29T00:05:05Z" level=info msg="GetRepoLabels(kubeflow, chainer-operator)" client=github 
time="2018-09-29T00:05:05Z" level=info msg="GetRepoLabels(kubeflow, internal-acls)" client=github 
time="2018-09-29T00:05:05Z" level=info msg="Listing labels for repo" org=kubeflow repo=marketing-materials 
time="2018-09-29T00:05:05Z" level=info msg="Listing labels for repo" org=kubeflow repo=arena 
time="2018-09-29T00:05:05Z" level=info msg="Listing labels for repo" org=kubeflow repo=examples 
time="2018-09-29T00:05:05Z" level=info msg="GetRepoLabels(kubeflow, arena)" client=github 
time="2018-09-29T00:05:05Z" level=info msg="GetRepoLabels(kubeflow, marketing-materials)" client=github 
time="2018-09-29T00:05:05Z" level=info msg="GetRepoLabels(kubeflow, examples)" client=github 
time="2018-09-29T00:05:05Z" level=info msg="Listing labels for repo" org=kubeflow repo=mxnet-operator 
time="2018-09-29T00:05:05Z" level=info msg="GetRepoLabels(kubeflow, mxnet-operator)" client=github 
time="2018-09-29T00:05:05Z" level=info msg="Listing labels for repo" org=kubeflow repo=fairing 
time="2018-09-29T00:05:05Z" level=info msg="GetRepoLabels(kubeflow, fairing)" client=github 
time="2018-09-29T00:05:06Z" level=info msg="Syncing labels for 22 repos" org=kubeflow 
time="2018-09-29T00:05:06Z" level=debug msg="{}\n" 
```

**Comment by jlewi** [comment]
Value of the config is

```
- color: d28caa
  name: addition/feature
- color: d2b48c
  name: area/api
- color: d2b48c
  name: area/0.4.0
  previously:
  - name: release/0.4.0
  name: area/build-release
  previously:
  - name: area/release-eng
  - name: area/releasing
- color: d2b48c
  name: area/docs
- color: d2b48c
  name: area/example
- color: d2b48c
  name: area/front-end
  previously:
  - name: area/ui
- color: d2b48c
  name: area/lifecycle
- color: d2b48c
  name: area/logging
- color: d2b48c
  name: area/operator
- color: d2b48c
  name: area/inference
  previously:
  - name: inference
- color: d2b48c
  name: area/usage
- color: ecfc15
  name: community/discussion
- color: ecfc15
  name: community/question
  previously:
  - name: question
- color: 00daff
  name: do-not-merge
- color: 00daff
  name: duplicate
- color: 00daff
  name: high-impact
- color: 00daff
  name: improvement/enhancement
  previously:
  - name: enhancement
- color: 00daff
  name: improvement/optimization
- color: 8cd2b4
  name: os/centos
  previously:
  - name: area/os/centos
- color: 8cd2b4
  name: os/macos
  previously:
  - name: area/os/macos
- color: 8cd2b4
  name: os/ubuntu
  previously:
  - name: area/os/ubuntu
- color: 8cd2b4
  name: os/windows
  previously:
  - name: area/os/windows
- color: 2515fc
  name: platform/aws
  previously:
  - name: area/platform/aws
- color: 2515fc
  name: platform/azure
  previously:
  - name: area/platform/azure
  - name: cloud/azure
- color: 2515fc
  name: platform/gcp
  previously:
  - name: area/platform/gke
  - name: cloud/gke
- color: 2515fc
  name: platform/minikube
  previously:
  - name: area/platform/minikube
- color: 2515fc
  name: platform/other
- color: db1203
  name: priority/p0
- color: db03cc
  name: priority/p1
- color: fc9915
  name: priority/p2
- color: fc2515
  name: kind/bug
  previously:
  - name: bug
  - name: problem/bug
- color: fc2515
  name: problems/refactor
  previously:
  - name: bug  
- color: fc2515
  name: problems/security
- color: 00daff
  name: starter
- color: 03db12
  name: approved
  previously:
  - name: status/approved
- color: ef1ad6
  name: area/0.2.0
  previously:
  - name: release/0.2.0
- color: ef1ad6
  name: area/0.3.0
  previously:
  - name: release/0.3.0
- color: ef1ad6
  name: area/1.0.0
  previously:
  - name: release/1.0.0
- color: bc9090
  name: status/backlog
- color: fca42e
  name: status/done
- color: '808080'
  name: status/icebox
# Don't remove, this label is being used by prow
- color: ffa500
  name: do-not-merge/work-in-progress
  previously:
  - name: status/in progress
- color: 2efca4
  name: lgtm
  previously:
  - name: status/lgtm
- color: 00daff
  name: area/testing
  previously:
  - name: testing
- color: 00daff
  name: wontfix
- color: 8cd2b4
  name: sprint/2018-05-29-to-06-08
- color: 8cd2b4
  name: sprint/2018-06-11-to-06-22
- color: 8cd2b4
  name: sprint/2018-06-25-to-07-06
- color: 8cd2b4
  name: sprint/2018-07-09-to-07-20
```
