### ISSUE TITLE
Test failures; out of firewall quota

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#328]
We ran out of firewall resource quota which is causing test failures.

See logs.

[kubeflow-presubmit-kfctl-2672-8dfc574-6263-3e11-2762981228.log.txt](https://github.com/kubeflow/testing/files/2964028/kubeflow-presubmit-kfctl-2672-8dfc574-6263-3e11-2762981228.log.txt)

**Comment by jlewi** [comment]
Here's an old firewall rule.

```
gcloud --project=kubeflow-ci compute firewall-rules describe k8s-fw-l7--c1eaafe584cd4f0e
allowed:
- IPProtocol: tcp
  ports:
  - '31831'
creationTimestamp: '2018-05-13T22:54:17.408-07:00'
description: GCE L7 firewall rule
direction: INGRESS
disabled: false
id: '8750559207085087334'
kind: compute#firewall
logConfig:
  enable: false
name: k8s-fw-l7--c1eaafe584cd4f0e
network: https://www.googleapis.com/compute/v1/projects/kubeflow-ci/global/networks/default
priority: 1000
selfLink: https://www.googleapis.com/compute/v1/projects/kubeflow-ci/global/firewalls/k8s-fw-l7--c1eaafe584cd4f0e
sourceRanges:
- 130.211.0.0/22
- 35.191.0.0/16
targetTags:
- gke-z-katib-presubmit-e2e-81-068f3fe-38-a8a0-092ed74e-node
```
