### ISSUE TITLE
Create a v0.5 KF cluster in kubeflow-releasing

### ISSUE THREAD

**Issue by jlewi** [kubeflow/testing#366]
Creating this issue to track updating of infrastructure in project kubeflow-releasing.

This cluster will be used for CI-CD.

We currently have a very old cluster in that project that we will get rid of.

**Comment by jlewi** [comment]
Here's some information about the old cluster

project:kubeflow-releasing
cluster: kubeflow-releasing


kubectl get jobs
NAME                  DESIRED   SUCCESSFUL   AGE
jlewi-image-release   1         0            214d

$ kubectl get all
NAME                                      READY     STATUS      RESTARTS   AGE
pod/argo-ui-6d5fd48cf9-nnfrp              1/1       Running     0          82d
pod/debug-worker-0                        1/1       Running     0          82d
pod/jlewi-worker-5f579679b6-dd4xd         1/1       Running     0          82d
pod/workflow-controller-8c4645697-cbwvw   1/1       Running     0          82d
pod/workflows-3357367425                  0/2       Completed   0          18d
pod/workflows-3861296723                  0/2       Completed   0          18d
pod/workflows-4136973007                  0/2       Completed   0          18d

NAME              TYPE       CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
service/argo-ui   NodePort   10.19.248.212   <none>        80:30098/TCP   353d

NAME                                  DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/argo-ui               1         1         1            1           353d
deployment.apps/jlewi-worker          1         1         1            1           214d
deployment.apps/workflow-controller   1         1         1            1           353d

NAME                                            DESIRED   CURRENT   READY     AGE
replicaset.apps/argo-ui-6d5fd48cf9              1         1         1         353d
replicaset.apps/jlewi-worker-5f579679b6         1         1         1         214d
replicaset.apps/workflow-controller-8c4645697   1         1         1         353d

NAME                            DESIRED   CURRENT   AGE
statefulset.apps/debug-worker   1         1         1y

NAME                            DESIRED   SUCCESSFUL   AGE
job.batch/jlewi-image-release   1         0            214d

$ kubectl get namespace
NAME                 STATUS    AGE
default              Active    1y
kube-public          Active    1y
kube-system          Active    1y
kubeflow             Active    1y
kubeflow-releasing   Active    1y

kubectl -n kubeflow get all
No resources found.

Going to delete that cluster.

**Comment by jlewi** [comment]
We also have a very old NFS share deployment; looks like this predates Cloud Fileshare. So going to delete that as well.

```
gcloud --project=kubeflow-releasing deployment-manager deployments describe singlefs-1
---
fingerprint: zfpef4BKTL2EIkcBlJ1cbw==
id: '5022851954378947733'
insertTime: '2018-02-22T18:54:51.021-08:00'
labels:
- key: cloud-marketplace
  value: click-to-deploy-images-singlefs
- key: cloud-marketplace-partner-id
  value: click-to-deploy-images
- key: cloud-marketplace-solution-id
  value: singlefs
manifest: manifest-1519354491085
name: singlefs-1
operation:
  endTime: '2018-02-22T18:55:22.946-08:00'
  name: operation-1519354490655-565d848b4111a-0c18bfad-b3b5d07d
  operationType: insert
  progress: 100
  startTime: '2018-02-22T18:54:51.705-08:00'
  status: DONE
  user: jlewi@kubeflow.org
NAME                TYPE                 STATE      INTENT
singlefs-1-coord    compute.v1.instance  COMPLETED
singlefs-1-vm       compute.v1.instance  COMPLETED
singlefs-1-vm-data  compute.v1.disk      COMPLETED
```
